# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('Type', models.CharField(choices=[(b'A', b'A'), (b'CNAME', b'CNAME')], max_length=50, verbose_name='\u7c7b\u578b')),
                ('ttl', models.IntegerField(choices=[(300, b'5 minutes'), (1800, b'30 minutes'), (3600, b'1 hour'), (43200, b'12 hours'), (86400, b'1 day')], verbose_name='ttl')),
                ('Data', models.GenericIPAddressField(verbose_name='IP')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'record\u7ba1\u7406',
                'verbose_name_plural': 'record\u7ba1\u7406',
                'permissions': (('can_read_bind_records', '\u8bfb\u53d6\u57df\u540d\u8bb0\u5f55\u6743\u9650'), ('can_change_bind_records', '\u66f4\u6539\u57df\u540d\u8bb0\u5f55\u6743\u9650'), ('can_add_bind_records', '\u6dfb\u52a0\u57df\u540d\u8bb0\u5f55\u6743\u9650'), ('can_delete_bind_records', '\u5220\u9664\u57df\u540d\u8bb0\u5f55\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='BindServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='bindIP')),
                ('dns_port', models.IntegerField(default=53, help_text='The port where the BIND server is listening for DNS requests. binder especially uses that port for the dynamic zone updates. In most cases you should always leave it at the default port 53.', verbose_name='DNS port')),
            ],
            options={
                'verbose_name': 'server\u7ba1\u7406',
                'verbose_name_plural': 'server\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='BindView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewname', models.CharField(max_length=255, unique=True, verbose_name='\u89c6\u56fe\u540d\u79f0')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'view\u7ba1\u7406',
                'verbose_name_plural': 'view\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='BindZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonename', models.CharField(max_length=255, verbose_name='\u4e8c\u7ea7\u57df\u540d')),
            ],
            options={
                'verbose_name': 'zone\u7ba1\u7406',
                'verbose_name_plural': 'zone\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='KEY\u540d\u79f0')),
                ('data', models.CharField(max_length=255, verbose_name='\u79c1\u94a5')),
                ('algorithm', models.CharField(choices=[('HMAC-MD5.SIG-ALG.REG.INT', 'MD5'), ('hmac-sha1', 'SHA1'), ('hmac-sha256', 'SHA256'), ('hmac-sha384', 'SHA384'), ('hmac-sha512', 'SHA512')], max_length=255, verbose_name='\u79c1\u94a5\u52a0\u5bc6')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bindview',
            name='default_transfer_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DNS.Key', verbose_name='\u6240\u5c5e\u5bc6\u94a5'),
        ),
        migrations.AddField(
            model_name='bindview',
            name='default_transfer_view',
            field=models.ManyToManyField(to='DNS.BindZone', verbose_name='\u6240\u5c5e\u57df'),
        ),
        migrations.AddField(
            model_name='bindview',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNS.BindServer', verbose_name='server'),
        ),
        migrations.AddField(
            model_name='bindrecord',
            name='bindzone',
            field=models.ManyToManyField(to='DNS.BindZone', verbose_name='\u6240\u5c5e\u57df'),
        ),
    ]
