# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNS', '0003_auto_20180711_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindrecord',
            name='bindzone',
            field=models.ManyToManyField(blank=True, null=True, to='DNS.BindZone', verbose_name='\u6240\u5c5e\u57df'),
        ),
    ]
