# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNS', '0004_bindrecord_bindzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindrecord',
            name='bindzone',
        ),
    ]
